### PR TITLE
fix: react to slot changes in group #18

### LINKED ISSUE #18: auro-accordion: accordion-group does not control expanded state if children added after connectedCallback is run
## Describe the bug
If child accordions are added to the accordion-group after connectedCallback has run, the accordion-group will not control the expanded state of these children.

This is especially an issue in Svelte, which first appends the group (calling connectedCallback), and then appends the children. At the time connectedCallback has run, the children are not in the DOM, so `this.items` is empty.

## To Reproduce
1. Render an accordion-group and accordions
2. Add an accordion to the group after initial load
3. Expand accordions and notice that the last accordion does not close when other accordions are opened

Alternatively, render the following markup inside Svelte. More than one accordion will be open at a time:

```html
<auro-accordion-group>
	<auro-accordion id="flightNotice">
		<span slot="trigger">Flight notifications</span>
		<p>
			By enabling flight notifications, you agree to the terms and
			conditions.
		</p>
	</auro-accordion>

	<auro-accordion id="dealsPromotions">
		<span slot="trigger">Deals and promotions</span>
		<p>More details</p>
	</auro-accordion>
</auro-accordion-group>
```

## Expected behavior
The accordion-group responds to child elements being added after initial render.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox

## Additional context
I think we can use the slotchange event to detect changes to the content slot.

### PR DESCRIPTION
**Pull request by geoffrich**
# Alaska Airlines Pull Request

Fixes #18

## Summary:

- listen to slot changes so that items is kept up to date. Previously, items was only set when the element was first connected. This caused issues in frameworks like Svelte that first mounted the group, and then the children.
- add related test that failed before the changes and now passes

## Type of change:

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by jason-capsule42 — APPROVED** [review]

File: src/auro-accordion-group.js [hunk 1]
```diff
@@ -31,10 +29,17 @@ class AuroAccordionGroup extends LitElement {
     });
   }
 
+  /**
+   * @private Internal function to update items when items are added or removed from the slot
+   */
+  handleSlotChange() {
```
Comment (blackfalcon) [inline src/auro-accordion-group.js:35]: This is an interesting accommodation to the typical standard of populating the slot element. Outside of the Svelte issue, this is an approach probably needed in any element if the content of the slot is to be dynamically updated outside of the initial callback.

Comment (blackfalcon) [reply src/auro-accordion-group.js:35]: This is to be documented.

File: test/auro-accordion-group.test.js [hunk 2]
```diff
@@ -25,12 +26,42 @@ describe('auro-accordion-group', () => {
...
     const button = accordions[0].shadowRoot.querySelector('button');
+
     button.click();
 
     expect(accordions[0].expanded).to.be.true;
     expect(accordions[1].expanded).to.be.false;
-  })
+  });
+
+  it('reacts to slot changes', async () => {
```
Comment (blackfalcon) [inline test/auro-accordion-group.test.js:38]: Given that this may become a boilerplate thing, it would be nice to template this test if possible.

**Review by blackfalcon — APPROVED** [review]

**Review by blackfalcon — APPROVED** [review]
