### PR TITLE
fix(a11y): correct aria-expanded and delegate focus

### LINKED ISSUE #167: a11y: Div element has aria-labelledby attribute that will not be used (low impact)
### What browser client(s) are you seeing the issue on?

- [x] Firefox
- [x] Chrome
- [x] Safari
- [x] Microsoft Edge

### What devices platform(s) are you seeing the issue on?

- [x] Desktop
- [x] Mobile

## See code

https://github.com/AlaskaAirlines/auro-accordion/blob/c2d5040aba11ed93611a12752859dec869a3c812/src/auro-accordion.js#L217-L221

## Description

One or more div elements, without an ARIA-assigned role, not intentionally hidden in the DOM and available to assistive technologies, has an aria-labelledby attribute.

## Why it matters

When an authored supplied accessible name is applied to the div element this name will not be seen by screen readers used by people who are blind or visually impaired.

## Recommendation

Remove `aria-labelledby="accordionTrigger"`. It adds no value to the hydrated content space and will be ignored by screen readers. 

### Expected behavior

No adverse behavior to report. 

### Which version of auro-templates do you have installed?

@latest

### Reproducible on the Auro doc site

- [x] I am able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com).

### Exit criteria (To be determined by the Auro team)

_No response_

### LINKED ISSUE #183: Programmatic focus is not handled properly
### What browser client(s) are you seeing the issue on?

- [x] Firefox
- [x] Chrome
- [x] Safari
- [x] Microsoft Edge

### What devices platform(s) are you seeing the issue on?

- [x] Desktop
- [x] Mobile

### Steps to reproduce

1. Go to accordion preview on doc site
2. Inspect an accordion DOM element (host element)
3. Right-click the DOM element and click "save as global variable"
4. In the console, type `temp1.focus()`, this will attempt to focus the accordion

### Expected behavior

**_Expected_**: focus shifts to the accordion's trigger
**_Actual_**: focus does not shift at all

### Which version of auro-templates do you have installed?

latest

### Reproducible on the Auro doc site

- [x] I am able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com).

### Exit criteria (To be determined by the Auro team)

Focus should be handled via delegatesFocus or by an internal focus method as we do in other components in order to shift the focus to the trigger when `.focus()` is called on the accordion.

### LINKED ISSUE #219: accordion does not announce expanded/collapsed on focus in screenreader
### What browser client(s) are you seeing the issue on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What devices platform(s) are you seeing the issue on?

- [ ] Desktop
- [ ] Mobile

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Which version of auro-accordion do you have installed?

_No response_

### Reproducible on the Auro doc site

- [ ] I am able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com).

### Exit criteria (To be determined by the Auro team)

_No response_

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Review Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

<details>
<summary>
RC Checklist
</summary>

### Browsers

[Browsers Support Guide](https://auro.alaskaair.com/support/browsersSupport)

[Dev demo link](https://alaskaairlines.github.io/auro-accordion/)

Android

- [ ] Chrome
- [ ] Firefox

 iOS

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Desktop

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Scenarios

- [ ] Validated linked issues with issue reporting team
- [ ] Test coverage report review

[Framework playground ](https://github.com/AlaskaAirlines/auro-framework-playground)

- [ ] Next React
- [ ] SvelteKit

</details><br>
**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

## Summary by Sourcery

Improve accessibility and focus behavior for the accordion component.

Bug Fixes:
- Correct the accordion trigger's ARIA attribute from `ariaexpanded` to the valid `aria-expanded` and remove an incorrect `aria-labelledby` reference from the content container.

Enhancements:
- Enable shadow DOM focus delegation on the accordion to improve keyboard focus handling for internal controls.

### CODE REVIEW

**Comment by jason-capsule42** [comment]
@sourcery-ai title

File: src/auro-accordion.js [hunk 1]
```diff
@@ -44,6 +44,15 @@ export class AuroAccordion extends LitElement {
   constructor() {
     super();
 
+    /**
+     * @private
+     * @property {boolean} delegatesFocus - Whether the shadow root delegates focus.
+     */
+    this.constructor.shadowRootOptions = {
+      ...LitElement.shadowRootOptions,
+      delegatesFocus: true,
```
[the remark this answers is not in the document]
Comment (jason-capsule42) [reply src/auro-accordion.js]: @sourcery-ai Give me an example of how to change the existing code to follow this suggestion.

File: src/auro-accordion.js [hunk 2]
```diff
@@ -270,7 +279,7 @@ export class AuroAccordion extends LitElement {
           class="${classMap(buttonClasses)}"
           id="accordionTrigger"
           aria-controls="${accordionContentId}"
-          ?ariaexpanded="${this.expanded}"
+          ?aria-expanded="${this.expanded}"
```
Comment (chrisfalaska) [inline src/auro-accordion.js]: This will completely remove the attribute when closed, which screen readers will interpret as "this element has no expand/collapse behavior."

https://lit.dev/docs/templates/expressions/#boolean-attribute-expressions

Instead, it should be:

`aria-expanded="${this.expanded}"`

which would set it to a sting of `"false"`.

Technically `aria-disabled="${this.disabled}"` on line `283` is the same issue, although it's effectively OK because not being present means "not disabled," which is the same as "`false`"

File: src/auro-accordion.js
Comment (chrisfalaska) [inline src/auro-accordion.js]: Typo. Should be: `ariaExpanded` with capital `E`

**Review by chrisfalaska — APPROVED** [review]
Tested with VoiceOver. Looks and sounds great! 🚀
